[package]
name = "chip8"
version = "0.1.0"
authors = ["Matthew Herman <mattherman11@gmail.com>"]

[dependencies]
piston_window = "0.61.0"
image = "0.12.4"
rand = "0.3"
clap = { version = "2.33.0", features = ["yaml"] }